In [2]:
import numpy as np
from numpy.linalg import *

In [2]:
a = np.array([[3,1],[1,2]])
b = np.array([9,8])

In [5]:
x = solve(a,b)

In [6]:
np.allclose(np.dot(a, x), b)

True

In [9]:
a = np.array([[1,1,-2],[1,3,-1],[2,1,-5]])
b = np.array([4,7,7])
solve(a,b)

array([-5.55111512e-16,  2.00000000e+00, -1.00000000e+00])

In [15]:
a = np.array([[1,1,-2],[1,3,-1],[2,1,-5]])
b = np.array([4,7,7])
solve(a,b)

array([-5.55111512e-16,  2.00000000e+00, -1.00000000e+00])

In [1]:
from sympy import *

In [24]:
x1,x2,x3,y1,y2,y3 = symbols('x1,x2,x3,y1,y2,y3')

In [25]:
f = (x2-x1)*(y3-y1) - (x3-x1)*(y2-y1)
f.expand()

x1*y2 - x1*y3 - x2*y1 + x2*y3 + x3*y1 - x3*y2

In [27]:
f = (17-x1)*(-18-x1) - 20*(-15)
f.expand()

x1**2 + x1 - 6

In [29]:
solve(f)

[-3, 2]

In [42]:
a = np.matrix('0 2;1 1')
a

matrix([[0, 2],
        [1, 1]])

In [43]:
eigvals(a)

array([-1.,  2.])

In [46]:
a = np.matrix('2 2;1 3')
a

matrix([[2, 2],
        [1, 3]])

In [47]:
eigvals(a)

array([1., 4.])

In [48]:
a = np.matrix('17 -15;20 -18')
a

matrix([[ 17, -15],
        [ 20, -18]])

In [49]:
eig(a)

(array([ 2., -3.]),
 matrix([[0.70710678, 0.6       ],
         [0.70710678, 0.8       ]]))

In [40]:
eigvals(a)

array([ 2., -3.])

In [16]:
a = diag(0,3,1)
type(a)

sympy.matrices.dense.MutableDenseMatrix

In [10]:
diag(sqrt(3),-2)

Matrix([
[sqrt(3),  0],
[      0, -2]])

In [27]:
a = np.matrix('  0 1 1 0 0 0;\
                 1 0 0 1 0 0;\
                 1 0 0 0 1 1;\
                 0 0 0 0 1 1;\
                 0 0 1 1 0 0;\
                 0 0 0 1 0 0')
a

matrix([[0, 1, 1, 0, 0, 0],
        [1, 0, 0, 1, 0, 0],
        [1, 0, 0, 0, 1, 1],
        [0, 0, 0, 0, 1, 1],
        [0, 0, 1, 1, 0, 0],
        [0, 0, 0, 1, 0, 0]])

In [29]:
a@a@a

matrix([[0, 2, 3, 2, 1, 1],
        [2, 0, 1, 3, 1, 1],
        [3, 0, 0, 1, 4, 4],
        [1, 0, 0, 0, 3, 3],
        [0, 1, 3, 4, 0, 0],
        [0, 0, 1, 2, 0, 0]])

In [32]:
np.diag([1,1,1,1])

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [38]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])