In [2]:
from numpy.linalg import *
import numpy as np

In [4]:
a = np.array([[1,3],[2,4]])
det(a)

-2.0

In [5]:
a = np.array([[1,0,2],[0,-1,3],[-2,-3,4]])
det(a)

1.0000000000000002

In [7]:
A = np.array([[4,-1,1],[2,3,5],[1,0,6]])
det(A)

76.0

In [10]:
B = np.array([[1,2,3],[0,-1,-2],[4,0,-3]])
det(B)

-1.0

In [11]:
B = np.array([[1,2,3],[-2,2,1],[5,0,-1]])
det(B)

-25.99999999999999

In [12]:
B = np.array([[0,2,3,0],[1,5,6,7],[-2,3,0,4],[-5,1,2,3]])
det(B)

318.0

In [13]:
A = np.array([[1,2,-1],[3,1,0],[-1,5,0]])
det(A)

-16.000000000000007

In [14]:
B = np.array([[3,2,0,-1],[0,6,0,0],[4,1,2,1],[3,-1,0,1]])
det(B)

72.0

In [24]:
C = np.array([[1,2,1,-1],[0,2,2,2],[0,0,-1,3],[0,0,0,1]])
det(C)

-2.0

In [26]:
C

array([[ 1,  2,  1, -1],
       [ 0,  2,  2,  2],
       [ 0,  0, -1,  3],
       [ 0,  0,  0,  1]])

In [28]:
CT = C.transpose()
CT

array([[ 1,  0,  0,  0],
       [ 2,  2,  0,  0],
       [ 1,  2, -1,  0],
       [-1,  2,  3,  1]])

In [31]:
det(C) == det(CT)

True

In [22]:
a = np.diag([3,3,3])
a

array([[3, 0, 0],
       [0, 3, 0],
       [0, 0, 3]])

In [23]:
det(a)

27.0

In [36]:
a = np.array([[0,1,3],[0,1,3],[5,2,6]])
b = np.array([[1,2,6],[1,4,-1],[0,1,3]])

In [37]:
det(a)

0.0

In [34]:
det(b)

64.99999999999999

In [43]:
!python3 --version

Python 3.8.5


In [44]:
!which python

/opt/anaconda3/envs/python3.8.5/bin/python


In [45]:
import pandas as pd

In [47]:
s = pd.Series([1, 3, 5, np.nan, 6, 8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [49]:
dates = pd.date_range('20130101', periods=6)
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [51]:
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list('ABCD'))
df

A         B         C         D
2013-01-01 -0.357425  0.079260  1.696581 -0.450507
2013-01-02 -1.080826 -0.716996 -0.946814 -1.084646
2013-01-03 -0.687167  0.615105 -0.654443  1.794143
2013-01-04  0.183680 -0.346544 -0.637870  2.213035
2013-01-05 -0.461335 -1.411678 -1.174230 -1.094972
2013-01-06  1.428065  0.959169 -1.147208 -1.523993

In [52]:
df2 = pd.DataFrame({'A': 1.,
                    'B': pd.Timestamp('20130102'),
                    'C': pd.Series(1, index=list(range(4)), dtype='float32'),
                    'D': np.array([3] * 4, dtype='int32'),
                    'E': pd.Categorical(["test", "train", "test", "train"]),
                    'F': 'foo'})
df2

A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [61]:
!pwd

/home/qslia


In [62]:
!cd gitclone/

In [63]:
!git clone https://github.com/PacktPublishing/Pandas-Cookbook-Second-Edition.git

正克隆到 'Pandas-Cookbook-Second-Edition'...
remote: Enumerating objects: 194, done.
remote: Counting objects: 100% (194/194), done.
remote: Compressing objects: 100% (137/137), done.(94/137)
remote: Total 194 (delta 56), reused 176 (delta 41), pack-reused 0
接收对象中: 100% (194/194), 40.22 MiB | 16.00 KiB/s, 完成.
处理 delta 中: 100% (56/56), 完成.


In [17]:
import numpy as np
from numpy.linalg import *

In [2]:
a = np.array([[2,4,-2,6],[-6,-6,-2,5],[1,1,3,-1],[4,6,-2,5]])
det(a)

20.000000000000007

In [3]:
a

array([[ 2,  4, -2,  6],
       [-6, -6, -2,  5],
       [ 1,  1,  3, -1],
       [ 4,  6, -2,  5]])

In [4]:
b = np.array([[1,3,1,5],[1,3,-3,-3],[0,3,1,0],[1,6,2,11]])
b

array([[ 1,  3,  1,  5],
       [ 1,  3, -3, -3],
       [ 0,  3,  1,  0],
       [ 1,  6,  2, 11]])

In [5]:
det(b)

72.0

In [6]:
12*7-8*4-3*23

-17

In [7]:
-4*23+28-18*4

-136

In [8]:
-17+136

119

In [10]:
c = np.array([[1,-4/3,23/6],[-1,4,-4],[-2,2,-7]])
det(c)*12

20.000000000000014

In [11]:
a = np.array([[3,0,1],[2,-1,4],[5,2,0]])
b = np.array([[-1,2,4],[7,1,0],[1,-2,3]])
a@b

array([[-2,  4, 15],
       [-5, -5, 20],
       [ 9, 12, 20]])

In [12]:
np.matmul(a,b)

array([[-2,  4, 15],
       [-5, -5, 20],
       [ 9, 12, 20]])

In [16]:
c = a.dot(b)
det(c)

1575.0000000000016

In [18]:
a = np.array([[1,1,2,-2,2],[3,3,5,0,2]])

In [21]:
b = np.array([[1,1,0,-7],[2,4,1,-16],[1,2,1,9]])

In [20]:
np.linalg.

2

In [22]:
matrix_rank(b)

3

In [23]:
A = np.array([[2,4,-1],[0,3,1],[6,-2,5]])

In [24]:
np.conjugate(A)

array([[ 2,  4, -1],
       [ 0,  3,  1],
       [ 6, -2,  5]])

In [27]:
a = np.matrix([[2,4,-1],[0,3,1],[6,-2,5]])
a

matrix([[ 2,  4, -1],
        [ 0,  3,  1],
        [ 6, -2,  5]])

In [28]:
det(a)

76.0

In [41]:
b = np.matrix('2 4 -1;0 3 1;6 -2 5')
b

matrix([[ 2,  4, -1],
        [ 0,  3,  1],
        [ 6, -2,  5]])

In [42]:
det(b)*inv(b)

matrix([[ 17., -18.,   7.],
        [  6.,  16.,  -2.],
        [-18.,  28.,   6.]])

In [37]:
a = np.diag([76,76,76])
b = np.matrix(a)
b

matrix([[76,  0,  0],
        [ 0, 76,  0],
        [ 0,  0, 76]])

In [38]:
det(a)

438976.0

In [39]:
det(b)

438976.0